services:

  db:
    image: postgres:16.9
    environment:
      POSTGRES_DB: integration_dbname
      POSTGRES_USER: integration_username
      POSTGRES_PASSWORD: integration_pw
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U integration_username -d integration_dbname" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: "0.50"
    #          memory: "225MB"

  api01: &api
    image: rinha-backend-payment-gateway:latest
    hostname: api01
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=integration_dbname
      - DB_USERNAME=integration_username
      - DB_PASSWORD=integration_pw
      - SERVER_PORT=8080
      - PAYMENTS_PROCESSOR_DEFAULT_URI=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_FALLBACK_URI=http://payment-processor-fallback:8080/payments
#      - JAVA_TOOL_OPTIONS=-Xms140m -Xmx222m
    ports:
      - "8081:8080"
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: "0.50"
  #          memory: "225MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: "0.20"
#          memory: "10MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
