services:

  db:
    image: postgres:16.9
    environment:
      POSTGRES_DB: integration_dbname
      POSTGRES_USER: integration_username
      POSTGRES_PASSWORD: integration_pw
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U integration_username -d integration_dbname" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./../config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
